// <auto-generated />
using System;
using DomesticoDireitos.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DomesticoDireitos.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260308020457_InitialDomestico")]
    partial class InitialDomestico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomesticoDireitos.Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("DomesticoDireitos.Api.Models.Diagnostico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("DomesticoDireitos.Api.Models.DiagnosticoItem", b =>
                {
                    b.Property<int>("DiagnosticoId")
                        .HasColumnType("int");

                    b.Property<int>("SubitemId")
                        .HasColumnType("int");

                    b.HasKey("DiagnosticoId", "SubitemId");

                    b.HasIndex("SubitemId");

                    b.ToTable("DiagnosticosItens");
                });

            modelBuilder.Entity("DomesticoDireitos.Api.Models.Subitem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Subitens");
                });

            modelBuilder.Entity("DomesticoDireitos.Api.Models.DiagnosticoItem", b =>
                {
                    b.HasOne("DomesticoDireitos.Api.Models.Diagnostico", "Diagnostico")
                        .WithMany("ItensSelecionados")
                        .HasForeignKey("DiagnosticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomesticoDireitos.Api.Models.Subitem", "Subitem")
                        .WithMany()
                        .HasForeignKey("SubitemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnostico");

                    b.Navigation("Subitem");
                });

            modelBuilder.Entity("DomesticoDireitos.Api.Models.Subitem", b =>
                {
                    b.HasOne("DomesticoDireitos.Api.Models.Categoria", "Categoria")
                        .WithMany("Subitens")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("DomesticoDireitos.Api.Models.Categoria", b =>
                {
                    b.Navigation("Subitens");
                });

            modelBuilder.Entity("DomesticoDireitos.Api.Models.Diagnostico", b =>
                {
                    b.Navigation("ItensSelecionados");
                });
#pragma warning restore 612, 618
        }
    }
}
